DROP VIEW MATRIKEL_INS_A.INS_BASICPROPERTYUNIT;

/* Formatted on 06/08/2018 11:39:29 (QP5 v5.269.14213.34769) */
CREATE VIEW MATRIKEL_INS_A.INS_BASICPROPERTYUNIT
(INSPIREID_LOCALID, INSPIREID_NAMESPACE, NATIONALCADASTRALREFERENCE, ADMINISTRATIVEUNIT, VALIDFROM, VALIDTO_NILREASON, BEGINLIFESPANVERSION, ENDLIFESPANVERSION_NILREASON, AREAVALUE, KOMMUNELOKALID)
BEQUEATH DEFINER
AS

SELECT DISTINCT
       s.ID_LOKALID AS INSPIREID_LOCALID,
       'http://data.gov.dk/inspire-cp/BasicPropertyUnit'
          AS INSPIREID_NAMESPACE,
       s.BFENUMMER AS NATIONALCADASTRALREFERENCE,
       'http://data.gov.dk/inspire-au' || '/' || j.KOMMUNELOKALID
          AS ADMINISTRATIVEUNIT,
       TO_CHAR (s.VIRKNINGFRA, 'YYYY-MM-DD"T"HH24:MI:SS.FF') AS VALIDFROM,
       'other:unpopulated' AS VALIDTO_NILREASON,
       TO_CHAR (s.REGISTRERINGFRA, 'YYYY-MM-DD"T"HH24:MI:SS.FF')
          AS BEGINLIFESPANVERSION,
       'other:unpopulated' AS ENDLIFESPANVERSION_NILREASON,
       (SELECT SUM (jj.REGISTRERETAREAL)
          FROM MATRIKEL_A.JORDSTYKKE jj
         WHERE     jj.SAMLETFASTEJENDOMLOKALID = j.SAMLETFASTEJENDOMLOKALID
               AND jj.REGISTRERINGTIL IS NULL
               AND jj.VIRKNINGFRA <= LOCALTIMESTAMP
               AND (jj.VIRKNINGTIL IS NULL OR LOCALTIMESTAMP < jj.VIRKNINGTIL))
          AS AREAVALUE,
       j.KOMMUNELOKALID AS KOMMUNELOKALID
  FROM MATRIKEL_A.SAMLETFASTEJENDOM s
       JOIN MATRIKEL_A.JORDSTYKKE j
          ON (j.SAMLETFASTEJENDOMLOKALID = s.BFENUMMER)
 WHERE     s.status = 'Gældende'
       AND s.REGISTRERINGTIL IS NULL
       AND s.VIRKNINGFRA <= LOCALTIMESTAMP
       AND (s.VIRKNINGTIL IS NULL OR LOCALTIMESTAMP < s.VIRKNINGTIL)
       AND j.status = 'Gældende'
       AND j.REGISTRERINGTIL IS NULL
       AND j.VIRKNINGFRA <= LOCALTIMESTAMP
       AND (j.VIRKNINGTIL IS NULL OR LOCALTIMESTAMP < j.VIRKNINGTIL);

COMMENT ON TABLE MATRIKEL_INS_A.INS_BASICPROPERTYUNIT IS 'INSPIRE: View til brug for INSPIRE WFS/GML-download: mappes til cp:CadastralParcels i http://inspire.ec.europa.eu/schemas/cp/4.0/CadastralParcels.xsd - laers, sdfe, 28. februar 2018. Viewet indeholder samlet fast ejendom';

GRANT SELECT ON MATRIKEL_INS_A.INS_BASICPROPERTYUNIT TO EJF_READ;

GRANT SELECT ON MATRIKEL_INS_A.INS_BASICPROPERTYUNIT TO GEOBANK_READ;

GRANT SELECT ON MATRIKEL_INS_A.INS_BASICPROPERTYUNIT TO KF_READ;